### ISSUE TITLE
space props ignored or overridden by defaultProps

### ISSUE THREAD

**Issue by lederer** [styled-system/styled-system#348]
When using the `space` function with defaultProps, I've found that passed props are sometimes ignored or overridden by the defaults. Specifically:

1: If defaults are defined via the `m` (or `p`) shortcut…

```jsx
Foo.defaultProps = {
  m: 4
};
```

… then props passed in via `m`, `m{x,y}`, or `m{t,r,b,l}` will be honored. ✅ 

2: If defaults are defined via `mx` or `my`…

```jsx
Foo.defaultProps = {
  mx: 4,
  my: 2
};
```

… then props passed via `mx` or `my` are honored ✅, but props passed via the `m` shortcut are overridden in the output CSS (as discussed in https://github.com/jxnblk/styled-system/issues/33) 😞, while props passed via `m{t, r, b, l}` are somehow ignored. 😕

3: If defaults are defined via `m{t, r, b, l}`…

```jsx
Foo.defaultProps = {
  mt: 1,
  mr: 3,
  mb: 2,
  ml: 2
};
```

… then props passed via `m{x,y}` or `m{t,r,b,l}` are honored ✅, but props passed via `m` are overridden (again, see https://github.com/jxnblk/styled-system/issues/33) 😕.

---

Though the case of `m` (or `p`) shortcuts being overridden by the more finely grained formats has come up before (https://github.com/jxnblk/styled-system/issues/33) I think it's worth revisiting because `defaultProps` is so core to how React is used. Arguably the author of a component should be free to use any of the `space` formats as defaults, while the consumer of a component should be free to use any as well, without knowing which formats were used in defaultProps.

Regardless, the case of `m{t,r,b,l}` props being ignored completely when defaults are defined via `m{x,y}` (in scenario 2 above) is new AFAICT.

Thanks for taking a look.

**Comment by Kikobeats** [comment]
I've experimented the same issue, that's my current workaround:

```
export default props => createElement(Box, { pr: 3, pl: 3, mb: 4, ...props })
```

**Comment by sarneeh** [comment]
I just wanted to create the same issue as I stumbled upon this problem. I guess it would be cool if default props like `my: 1` would be always **replaced** by direction-specific props like `mb: 2` resulting in `margin-top: 8px` and `margin-bottom: 16px` CSS.

**Comment by jxnblk** [comment]
In keeping close to how CSS itself works, using shorthand properties will cause issues like this to happen. This library doesn't really work at the React level (involving `defaultProps` etc.), and to handle things like this, you might want to wrap your own component to account for edge cases like this. With styled-system, `x` and `y` directions override the singular directions (which is a decision made for this library) and changing that behavior could cause potentially breaking changes elsewhere – I don't think there's really a good solution that would avoid a breaking change like that, but open to see suggestions for implementations

**Comment by lederer** [comment]
Thanks for taking a look. Your comment led me to think through it more fully and I understand where you landed on it and why it's not realistic to address.

I think @sarneeh's idea would help make things more predictable at least: to always replace shortcuts with direction-specific props, or more generally, to always allow the most specific prop to win. IIUC, due to the way [space props are currently sorted (alphabetically) and merged](https://github.com/jxnblk/styled-system/blob/master/src/index.js#L204):
- `m[trbl]` overrides `m` (specificity wins) ✅
- `m[xy]` overrides `m` (specificity wins) ✅ 
- `m[xy]` overrides `m[trbl]` (specificity loses) 😞

**Comment by jxnblk** [comment]
With the changes in #513 prop order should now take precedence, meaning whatever is defined last should override. If anyone has a chance to try out the prerelease, that’d be super helpful

**Comment by cereallarceny** [comment]
@jxnblk [I wrote a quick CodeSandbox to explain the issue visually.](https://codesandbox.io/s/amazing-bhaskara-bqz5k?fontsize=14)

To me, this issue is super frustrating.  I feel that whatever you set as a `defaultProps` should be just that... a "_**default**_ prop".  If I select `{ m: 0 }` as my default margin for an image, why is it that the only value that will override this is another `m` prop?  It seems obvious to me that any value that conflicts with the default should override it - be it an `my`, `mb`, another `m`, or whatever.

Tangentially this has been my biggest frustration when using Rebass ([even when using the `update-styled-system` branch which bumps the library to v5](https://github.com/rebassjs/rebass/tree/update-styled-system)).

**Comment by jxnblk** [comment]
Because `m` and `m[trblxy]` are all different props, using a default prop will only apply to the props you specify. Styled System only returns styles objects and doesn't do anything with React or the actual CSS generation, so I'm not sure that there's anything related to this that this library can do on its own, other than advise against using conflicting CSS rules between different props. Closing this for now, since styles are applied in the order they're given and that should give the end user more control over how things work

**Comment by cereallarceny** [comment]
With all due respect @jxnblk - I'm not sure that's really an answer to the problem.  Personally, I'd imagine most of the people in this thread consider this to be something that should be changed in the library.  There's not a ton of properties that would need this exception, I'm sure it wouldn't be a hard fix to make.

To provide an example, I know I've spent hours trying to figure out why `margin`, `padding`, and `border` props aren't applying.  If I'm creating a component library for other junior developers on my team to use, how clear will exception this be for them?  I don't think it's terribly obvious.

Enough complaining from me - if you'd like the help, I'd love to take a stab at this in a PR if you're open to it.  Of course, if you're not interested in moving from your position, I'll respect that and move on.  😄

**Comment by jxnblk** [comment]
@cereallarceny 

> I'm sure it wouldn't be a hard fix to make

The difficult parts in my mind is 1) non-breaking change, 2) staying true to how CSS behaves, and 3) not coupling this library with React or any CSS-in-JS solution. The `m` and `mx` are still different props, and making them contextually aware of other props seems like it'd require a little bit of "magic" to work.

> if you'd like the help, I'd love to take a stab at this in a PR if you're open to it

Yes, I am certainly open to proposals on how to make this better. This particular issue was opened on a previous version of the library, and the changes in v5 make some of the things discussed here inaccurate since order of props affects precedence now
