### ISSUE TITLE
[Question] Avoiding apropcalypse using styled-system

### ISSUE THREAD

**Issue by sarneeh** [styled-system/styled-system#394]
So I've been working with `styled-system` for a while already, but unfortunately, I often struggle with making my components too modular which ends up having a real "apropcalypse".

Consider having a primitive `ListItem` component:

```js
const ListItem = styled.ul`
    ${space};
}
```

Everything is awesome for now, I can put a `ListItem` easily and add some paddings and margins. But now I want to use it in my `Nav` element, and it needs to be `inline-flex`. And we also want to show a dropdown on the `ListItem` hover right below it, so I'd need a `relative`.

What would you do in this situation?

1. Add additional style functions to `ListItem` and use it explicitly in `Nav`:
```js
const ListItem = styled.ul`
    ${space};
    ${display};
    ${position};
`;

...

<Nav>
    <ListItem display="inline-flex" position="relative">
        ...
    </ListItem>
</Nav>
```

or

2. Create a `NavListItem` component which extends the `ListItem` one:
```js
const ListItem = styled.ul`
    ${space};
`;

...

const NavListItem = styled(ListItem)`
    display: inline-flex;
    position: relative;
`;

...

<Nav>
    <NavListItem>
        ...
    </NavListItem>
</Nav>
```

The thing is, `styled-system` gives a lot of flexibility and I guess It's so big that I'm getting lost in it :smile: 

So, my question is: what pattern would you recommend to go with `styled-system` - to create minimal primitives and use them to create context-specific components by extending the primitive ones, or rather create big, extensive primitives and just build up context-specific components out of them (composing with available props)?

**Comment by jxnblk** [comment]
I think for one-off contextual styles like in your example, I'd tend to either extend the base component like your second example **or** use the `css` prop, which is really great for one-off styling. Generally I wouldn't recommend adding style props unless they are really, truly reusable props (e.g. spacing and color). Also for positioning, I tend to prefer explicit `<Relative />` and `<Absolute />` type components since CSS positioning is a footgun.

That said, it really just comes down to your team's preference and there are a lot of different ways to handle these sorts of things

**Comment by sarneeh** [comment]
@jxnblk Thanks a lot for your answer!

The problem I have with explicit `<Relative />` and `<Absolute />` components is that I often end up needing a specific markup, i.e. creating a `nav`, where I need a `li` with `position: relative` to show an `absolute` dropdown below it, but I can't do `<Relative><li>...</li></Relative>` as `ul`'s with `div` descendants is not semantically correct. (The dropdown also shouldn't be wrapped with `<Absolute />` as it should be another `ul`). But that's just an example - I often get things like that if I want the semantics right.

Do you maybe know more projects with `styled-system` usage (except the ones listed in the docs - `rebass` and `priceline`) to look at and grasp some inspiration?

**Comment by jxnblk** [comment]
For `<li>` you can nest the `<Relative />` inside the item **or** use the `as` prop if needed. You should be able to follow css-in-js and react patterns while maintaining semantic markup

**Comment by sarneeh** [comment]
One more question: do you rather aim for the reuse of primitives with style props i.e. `const ProductCard = styled(Card)``` or add them explicitly when needed? I often wonder if I should extend a style-prop-rich primitive to create a new component (even if I won't use most of the style props) or just do `const MyComponent = styled.div` ${neededStyleProp}; `.

Sorry if the questions may sound trivial, I just don't know much people with experience with this kind of approach and would like to hear about experiences and get some guidance :smiley:

**Comment by simoneb** [comment]
@sarneeh I found myself dealing with a codebase where styled-system was used. My solution eventually was to not use styled-system 😉

**Comment by sarneeh** [comment]
@simoneb Could you elaborate why? :)

**Comment by nicholaai** [comment]
@sarneeh, i reuse the primitives. otherwise you're recreating different types of cards over and over. 

also, lol @ coming in a thread just to say you don't want use styled-system, @simoneb. nice.

**Comment by sarneeh** [comment]
@nicholaai Thanks for your answer! Can I ask what kind of primitives you usually introduce? And how do you handle specific styling like `position` or hiding things around for different media with `display: none`? Do you bundle a `position` and `display` to the primitives, or style it ad-hoc?

**Comment by simoneb** [comment]
@sarneeh @nicholaai didn't mean to troll 😅  Here's a more elaborate answer.

Take @sarneeh's example. In the first case, you end up filling your styled-component definition with so many styled-system props for each individual use case you need to cover that the result is a generic component which could do pretty much anything. 
If you then imagine that you could use styled-component's `as` property, you can build your entire application with a single React component which can transform into any DOM element with any properties. That's clearly not what you want to do.

In the second case, which in my opinion is a more correct way to implement a component hierarchy, you are extending `ListItem` with `NavListItem`. Now, are you really sure that you need the flexibility that the `space` helper gives you on the `ListItem` component? I mean, what do you need it for? 

If you want to get rid of the user agent default padding/margin on the `ul` element then you probably want to do it consistently across the application, meaning that you don't need to use styled-system helpers and you can hardcode your values, either in a base component or with global styles. If that's for contextual spacing for layout, then that's probably not where you should put paddings and margins, but rather in a layout container which wraps your `ul`.

Either way, you don't need any styled-system helpers. 

The other feature that styled-system has are the spacing, font sizes, ..., arrays, which you can reference by array indexes. I found this very hard to use because you have to remember all the time what an index in that array corresponds to. Then at some point you come across a value for spacing that doesn't exist in your array and if you want to modify it you have to change *all places* in the application where you were using the array indexes. I find this problem better solved by using a consistent typography (i.e. using Typography.js, material-ui, or simply global styles), and consistent spacing. Defining a base spacing unit configured in the theme and using multipliers of it does the trick for me, and it's also the approach used in other libraries.

Because of this, the only real feature which styled-system offers that is not built into styled-components is responsiveness, but using it I figured that you can easily do without. First of all, using arrays for specifying responsive CSS properties can easily turn into a nightmare in the same way as described above. Then, I'm not sure it's great to have to provide all those verbose properties when the components are used. Instead, I simply use [responsive utilities](https://www.styled-components.com/docs/advanced#media-templates) for styled-components or if you need greater flexibility just use a UI toolkit like material-ui.

Hope it helps!

**Comment by jxnblk** [comment]
@sarneeh until we get some better examples up, you might have better luck asking some questions on Spectrum: https://spectrum.chat/styled-system – *or* maybe opening more specific questions as new issues since this conversation has derailed a bit. Styled System is intentionally very flexible so there's no real right or wrong way to use it, just how you and your team prefer

Possibly relevant thread here as well: https://spectrum.chat/styled-components/general/using-styled-system-vs-pure-styled-components~b9afb6f3-a675-4f97-bc78-66411292fab1

**Comment by sarneeh** [comment]
@simoneb Thanks a lot for this answer! Actually, according to the responsive props, you can now use object notation like: `width={{ sm: 1, xl: '50%' }}` which eliminates the index issue (which really was a pain).

@jxnblk Sure thing! I'll maybe move the discussion there :smile: 

Thanks everyone for your insights!
