### ISSUE TITLE
Variant styles should be able to take in props for conditional styling

### ISSUE THREAD

**Issue by paulsherwinang** [styled-system/styled-system#462]
Hi!

Great work, Im actively using this library in my current project now! I was just wondering if variant could check the theme object by key, and if that variant style is a function, that takes in props to return conditional styles based on it. Do you think that will be possible? I saw that the variant util function is only taking into consideration an object and just returns that directly

Thank you, and great work by the way! :)

**Comment by jxnblk** [comment]
Sorry for the delay on this. It sounds like what you're describing would be possible, but I'm not sure I entirely understand the use-case for this sort of thing. If you have an example (or example code) to demonstrate the intended API, that might be helpful. Generally I tend to think that the `theme` object should be mostly static/JSON-serializable and that any logic that deals with props should happen at the component level (if that makes sense)

That said, I'm leaning more towards using the [`@styled-system/css`](https://styled-system.com/css/) package for situations where there's mixing of styled-system props and style objects, but there might be some interesting additions to the `variant` utility (or a separate utility) that might be nice to have

**Comment by skrivanos** [comment]
@jxnblk Chiming in here hoping to get this opened again... I agree with you in theory – logic in theme is kind of ugly. However, in practice it becomes pretty much necessary in some cases. 

In our case, we have components with a bunch of different states depending on various props (e.g. isSelected, isFocused). We also need to be able to change the look of these components using variants, e.g. light and dark. We can't place the overrides in a separate theme since both variants are used simultaneously. This means that we'd need to access the supplied props in the theme in order to change how they look for each state. 

What we end up having to do now is assigning a className for each state as well and theming using that `&.isSelected: {...}`. This is of course not ideal and it would be much preferable to be able to use props.

Is there another recommended approach here? I'm starting to wonder if we're using the library in the wrong way.
