### ISSUE TITLE
Align breakpoints with Material UI breakpoints

### ISSUE THREAD

**Issue by mbmohib** [styled-system/styled-system#581]
Currently, we are using Material-UI with styled-component and styled-system using the same theme file. The material-ui breakpoint is a nested object with keys and values properties. 

So I can't use for a responsive style like mt={sm: 1, md: 2}

How to solve this?

**Comment by angeloashmore** [comment]
@mbmohib I'm not sure if this answers your question, but `styled-system` supports object responsive styles: https://styled-system.com/responsive-styles#using-objects.

**Comment by jxnblk** [comment]
For Styled System you can define `theme.breakpoints` as an array *or* object, but it needs to be defined in the way this library expects it. You should be able to create a theme object that works with both libraries, but you'll probably need to provide the same breakpoints for each one since Material UI does not follow the same theme specification

**Comment by mbmohib** [comment]
@jxnblk sorry for the late reply, in my material ui theme file, my breakpoints are defined like this: 

```
breakpoints: {
    keys: ['xs', 'sm', 'md', 'lg', 'xl'],
    values: { xs: 0, sm: 600, md: 960, lg: 1280, xl: 1920 },
}
```

So now, How I use breakpoints in both of this?

**Comment by rasovica** [comment]
Rtfm: https://styled-system.com/responsive-styles#using-objects
```const breakpoints = ['576px', '768px', '992px', '1200px'];

// aliases
breakpoints.sm = breakpoints[0];
breakpoints.md = breakpoints[1];
breakpoints.lg = breakpoints[2];
breakpoints.xl = breakpoints[3];

export {breakpoints};
```
