### ISSUE TITLE
defaultProps for px overrides specified prop pr or pl

### ISSUE THREAD

**Issue by mrcoles** [styled-system/styled-system#599]
See this codesandbox: https://codesandbox.io/s/styled-systemdefaultprops-issue-yogqm

If I give a box component defaultProps = `{ px: '40px' }`, then when I specify `pr={'200px'}` without specifying `px`, the defaultProps value takes precedence over the specified one.

I would expect the opposite to happen.

**Comment by sapegin** [comment]
Same with `m` vs `mt`/`mb`/`ml`/`mr`. 

And it used to work in v4. 

I guess we can change the order or props here:

https://github.com/styled-system/styled-system/blob/25c6e4d49f6b9e3154a59a5a3f4ed1a463ee27f7/packages/space/src/index.js#L24-L66

**Comment by Jaewoook** [comment]
It didn't solved yet? I can't upgrade to v5 because of this issue.

**Comment by jxnblk** [comment]
Styled System props take precedence based on order. The `px` and `pr`/`pl` props are *different* props, so setting one as a React `defaultProp` is going to behave differently than setting a default prop and overriding that same prop. Since this is built-in to how React works, and Styled System does not use React internally, I don't think there's much this library can do other than advise against trying to override default props with a different prop

In your Sandbox example, the order of the props matter:

```jsx
// pr takes precedence:
<Box px={1} pr={2} />

// px will take precedence
<Box pr={2} px={1} />
```

If you have `px` set as a default prop, you can reset that prop value inline in JSX before using a single directional prop, but obviously this is a sort of awkward API for the end user:

```jsx
// with Box.defaultProps.px
<Box px={0} pr={2} />
```

I'd say try to keep this in mind when setting defaultProps on a component, but `px` and `pr` are different props as far as React is concerned. The `px`/`py`/`mx`/`my` helpers should only really be used when you want symmetrical margin or padding applied. For asymmetrical values, I'd recommend using the single direction props

**Comment by mrcoles** [comment]
@jxnblk I’m not fully understanding what “this” is in “this is built-in to how React works”. Are you saying that React applies values for `defaultProps` to the *end* of a component’s props iff that prop is not specified and that’s why the default props end up taking precedence in this example?

It also sounds since you’re saying the order of the props in the component is what matters, that  @sapegin’s suggestion for reordering `configs.margin` and `configs.padding` would have no value?

**Comment by jxnblk** [comment]
The `px` and `pr` props are different props, that's what I meant by *this is how React works*. The order of the props in the component is what determines the source order of the CSS with v5, so I don't think reordering the config object would make a difference (I might be misunderstanding the suggestion though)

**Comment by mrcoles** [comment]
@jxnblk I was unclear about the “Are you saying that React…” part. I went ahead and wrote a quick demo to validate it and I am now seeing—as you were implying—that **React adds missing defaultProps to the end of a component’s props**. That’s really unintuitive (for React to do it that way), but helpful to now know!

Given that knowledge, yeah, I do not see how @sapegin’s comment would help either.

Bummer, but thanks for replying!

P.S. - here’s the defaultProps test code: https://codesandbox.io/s/react-defaults-props-vs-props-ordering-mmr0r

**Comment by sapegin** [comment]
This is the only solution I found — creating a wrapper component and applying default props manually as props:

```jsx
const HeadingBase = styled.h1`
  ${space};
   /* Other styles */
`;

// Apply default props manually, because styled-system will apply them after
// passed props, so default m prop will overwrite passed mb prop for example
const Heading = props => <HeadingBase {...Heading.defaultProps} {...props} />;

Heading.defaultProps = {
  m: 0,
  size: 'xl',
};
```
