### ISSUE TITLE
How do you decide what should be a systemProp?

### ISSUE THREAD

**Issue by siddharthkp** [styled-system/styled-system#608]
Heyo!

While I was building a button group, I found myself reaching out for a granular radius prop like `borderTopLeftRadius`.

![button group screenshot](https://user-images.githubusercontent.com/1863771/61454461-99092e80-a97e-11e9-96b9-8018a4d71b84.png)

[`@styled-system/border`](https://github.com/styled-system/styled-system/blob/master/packages/border/src/index.js) doesn't support it out of the box. 

Granular props do exist for some other properties like `padding`, `margin`, `border`, but not `borderRadius`

Now, even though this is easily possible in userland by creating a custom prop, I wonder how do you decide what goes inside the system and what lives in user land. I can imagine this would get out of hand pretty fast (there are ~ [565 distinct property names!?](https://www.w3.org/Style/CSS/all-properties.en.html#list))

What do you think about this? (also, does something like borderTopLeftRadius pass the test?)

**Comment by jxnblk** [comment]
I wrote a response to this yesterday, but just now noticed it didn't actually post... 😞I'll try again

With the first version of Styled System, I really tried to focus on style props that would be likely to change on a per-instance basis in a UI, i.e. margin, padding, width, font-size, color, and background-color. Properties like border and CSS grid came later as others were asking for them, but *personally* I wouldn't use many of the properties that are built-in now as style props. With v5, I've tried to streamline the API for custom style props to make that the preferred way to handle other properties that aren't built in.

That said, when I look at your button group example, I wouldn't want to add a prop like `borderTopRightRadius` on the buttons because it would make it very easy to do the "wrong" thing and apply a border radius in a strange place outside of the button group. Instead, I'd probably make a `ButtonGroup` component that wraps `Button` and applies border radii to the first and last child (probably using `React.Children`), which would result in a less flexible but more foolproof API.

E.g.

```jsx
<ButtonGroup>
  <Button>Beep</Button>
  <Button>Boop</Button>
</ButtonGroup>
```

That said, every project and team is different, so if you want to add a `borderTopLeftRadius` prop, I'd suggest creating [custom props](https://styled-system.com/custom-props).

**Comment by siddharthkp** [comment]
> I wrote a response to this yesterday, but just now noticed it didn't actually post... 

sigh, same.

Cool got my overall answer. 👍 

and...

> I wouldn't want to add a prop like borderTopRightRadius on the buttons because it would make it very easy to do the "wrong" thing

Yeep! That's a great point.

> I'd probably make a ButtonGroup component that wraps Button and applies border radii to the first and last child (probably using React.Children)

I'm doing exactly this but trying to use the same API. 
- Created a custom prop `borderTopLeftRadius`
- Passing it down to the `Button` from `ButtonGroup`

Why? 
To create one way of styling elements: passing system props.

This does have the problems you mentioned - Now the `Button` supports the custom prop for all scenarios (open to strange use).

Is this a silly goose to chase? Would you recommend overriding the style in parent (ButtonGroup) with `@styled-system/css` instead?

**Comment by jxnblk** [comment]
> Is this a silly goose to chase? Would you recommend overriding the style in parent (ButtonGroup) with @styled-system/css instead?

While generally I recommend avoiding child selectors, I think in components like `ButtonGroup`, the odds of ending up with a large element tree as children is fairly low, if you use direct child selectors (`& > button`), I think it's an okay way to go. Though I do like the purity of having one method to style everything, I think it's okay to have more component-specific styles tucked away in a component's implementation

**Comment by siddharthkp** [comment]
Thanks for taking the time to answer this! Appreciate it!
