### ISSUE TITLE
enable custom "prop" to breakpoints

### ISSUE THREAD

**Issue by sibelius** [styled-system/styled-system#651]
We are having trouble using styled-system v5 with material-ui because `createMuiTheme` will create the following breakpoint as an object

![image](https://user-images.githubusercontent.com/2005841/62397952-a6f9aa80-b54d-11e9-891b-96e69dd02dae.png)

```jsx
{
  "breakpoints": {
    "keys": [
      "xs",
      "sm",
      "md",
      "lg",
      "xl"
    ],
    "values": {
      "xs": 0,
      "sm": 600,
      "md": 960,
      "lg": 1280,
      "xl": 1920
    }
  },
}
```

can we have a `prop` on `theme` that says the `key` of breakpoints?

```jsx
const theme = {
   customBreakpoints: 'ssBreakpoints',
   ssBreakpoints: [],
}
```

**Comment by jxnblk** [comment]
Material UI uses its own custom fork of Styled System, but you could probably add appropriate keys to the `theme.breakpoints` object that it returns that could work with Styled System.

E.g.
```js
theme.breakpoints[0] = '40em'
theme.breakpoints[1] = '52em'
/// etc...
```

This library follows the [Theme Specification](https://github.com/system-ui/theme-specification), and it's not really in the interest of this effort to allow customization of the theme shape here

**Comment by sibelius** [comment]
@oliviertassinari any way to use theme specification on material-ui?

**Comment by oliviertassinari** [comment]
@sibelius This is an interesting interoperability issue, I wasn't aware of it, thanks for raising. I have been keen on improving the breakpoint structure of the Material-UI themes since we first introduced it in v1 alpha. I'm [not very happy](https://trello.com/c/JlTEy79C/1376-simplify-breakpoint-structure) with the way it can be used/customized right now. @jxnblk is right, Material-UI system started as [a fork of smooth-ui's system](https://material-ui.com/system/basics/#prior-art), authored by an ex-coworker/friend to match our existing theme structure, also influenced by the great work done on styled-system.

While changing the theme structure can be a significative issue from a backward compatibility perspective for the developers using Material-UI, I still think that we have some room for changes and innovation in the version 5 (probably in May 2020).

Here is an idea to explore, we could be using the same structure as Bootstrap: https://getbootstrap.com/docs/4.3/layout/grid/#grid-tiers, (most of our users are coming from Bootstrap, we are doing our best to leverage common conventions developers have already learned).

```jsx
const theme = {
  breakpoints: {
    values: {
      xs: 0,
      sm: 600,
      md: 960,
      lg: 1280,
      xl: 1920,
    },
    up,
    down,
    between,
    only,
  },
}
```

So dropping the `keys` and `width` property, it's redundant. It's also similar to Uber approach: https://baseweb.design/components/block/#responsive-layouts. We might even be able to introduce the change without a breaking change in v4 :).

I'm not sure how we could help in this case 🤔.

> any way to use theme specification on material-ui?

I want each breakpoints value to be named. I don't see how an array structure is rich enough. Is there a way to do it?

I'm wondering, how are styled-components users writing media queries right now? We document the following in Material-UI, could we make it simpler?: 
```jsx
import styled from 'styled-components';

const StyledButton = styled.button`
  padding: 8px 12px;
  border: 1px solid;
  cursor: pointer;
  outline: none;
  font-size: 18px;
  ${props => props.theme.breakpoints.up('md')} {
    font-size: 16px;
  }
`;
```
