### ISSUE TITLE
Feature Request: Negative values for position props

### ISSUE THREAD

**Issue by slightly-askew** [styled-system/styled-system#703]
I'm using the position prop in a component like so:

`top={[0, 0, 0, 0, -3]}`

I expected that that the `-3` value would respect the 4th value in my `space` theme, except for turning the value into a negative, in the same manner as the margin props allow for negative theme values.

The actual result was that the value moved my element `-3px`

**Comment by ShadOoW** [comment]
Hello,

I'm using negative values from my theme without a problem.
Here an example from my code

```
<Flex
      mx={-2}
>
```

You may wanna try it with margin prop to see if the problem is media query specific.
You may also want to update to the latest version, because I think I remember this to be a recent feature added (not sure could be wrong).

**Comment by jxnblk** [comment]
Currently only margin supports negative theme-based values. You can use margin props alongside position props, or you can hard-code the position value that you're trying to use, e.g. `-16`

**Comment by slightly-askew** [comment]
Yep, sure thing :) 

Aside from hard coding the value (which I did), I could have fallen back to my `useScale` hook if I really really wanted it to pull from theme values.

Feel free to close this if it's an intentional decision - I just thought having consistent behaviour between margin and position props might make the expected outcome more predictable.
