### ISSUE TITLE
Warnings with styled-components v4.4.0

### ISSUE THREAD

**Issue by alexandernanberg** [styled-system/styled-system#848]
**Describe the bug**
Warnings is logged to the console

**To Reproduce**

Go to https://codesandbox.io/s/silly-nightingale-nffhf and check the console

**Expected behavior**
No warnings logged

**Screenshots**
N/A

**Additional context**
N/A

**Comment by grabbeh** [comment]
The error message is because styled-system expects a theme object to be provided that it can draw various values from. The absence of that theme explains the error.

Suggest you take a look here https://styled-system.com/getting-started and the use of `ThemeProvider`. 

I also updated the sandbox to give an example of how I would achieve what you're looking to do, including through adding in the `ThemeProvider` component. 

https://codesandbox.io/s/spring-smoke-qcxrh

As an aside, my understanding is that `system` is used for non-standard CSS values (although I guess maybe  here you're looking to expand `bg` to `backgroundColor` to make it clearer?).

**Comment by alexandernanberg** [comment]
Yeah I'm aware of that but I don't think the ThemeProvider should be required right? I'm still not sure where this issue belongs, I've opened one in the styled-components repo as well https://github.com/styled-components/styled-components/issues/2766

**Comment by Pipo93** [comment]
I agree that ThemeProvider should not be required since there are many use cases where you just want to specify some basic styling without having a theme for that...

**Comment by alexandernanberg** [comment]
Fixed in the latest styled-components release
