### ISSUE TITLE
Border prop order

### ISSUE THREAD

**Issue by rich-wvs** [styled-system/styled-system#984]
When adding border props, you need to make sure they are in a specific order, otherwise they do not work. For example you need to specify "border" or "borderRight" etc before "borderColor". I know that when typing out the CSS property you would specify "1px solid" before "red", but I don't think there should be an issue with the order in which you apply the props.

To reproduce, try something like:

<Column
     borderColor={["red", "red"]}
     borderRight={["0", "1px solid"]}
     width={[1, 1 / 2]}
>

**Comment by jxnblk** [comment]
If you've opted to use CSS shorthands like `border` and `border-right` instead of `border-width`, `border-style`, and `border-color`, source order will matter, and there's not much Styled System can do to prevent that from happening. I'd suggest *not* mixing shorthand CSS properties with the regular ones

**Comment by jxnblk** [comment]
Closing in favor of #1058
